name: Deploy portfolio to mini PC

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Actualizar c√≥digo del portfolio en el servidor
        run: |
          cd /srv/apps/portfolio
          git fetch origin
          git reset --hard origin/main

      - name: Reconstruir solo el servicio de portfolio
        run: |
          cd /srv
          docker compose up -d --build portfolio
